# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "Dockerfile"
    ignore:
      # We must handle major.minor Go releases manually due to direct feature support
      - dependency-name: "library/golang"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      # Node v25 stopped shipping corepack which we need
      - dependency-name: "library/node"
        update-types:
          - "version-update:semver-major"
      # We must handle major.minor Rust releases manually since they might introduce changes breaking tests
      - dependency-name: "library/rust"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "pydantic-core"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
