# Project information
site_name: Hermeto
repo_name: hermetoproject/hermeto
repo_url: https://github.com/hermetoproject/hermeto
edit_uri: edit/main/docs

# Theme configuration
theme:
  name: material
  locale: en
  palette:
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/brightness-5
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.tooltips
    - navigation.sections
    - search.share
    - search.suggest

# Navigation bar
nav:
  - Home: index.md
  - Usage: usage.md
  - Package managers:
      - bundler: bundler.md
      - cargo: cargo.md
      - generic: generic.md
      - gomod: gomod.md
      - npm: npm.md
      - pip: pip.md
      - yarn classic: yarn_classic.md
      - yarn berry: yarn.md

# Markdown extensions
markdown_extensions:
  - toc:
      permalink: true

# Markdown validation
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn

# Irrelevant files
exclude_docs: |
  dependency_confusion.md
  adr/
  design/
